[package]
name = "mdbook-scala-wrapper"
version = "0.1.0"
authors = ["Noel Welsh <noel@inner-product.com>"]

[dependencies]
clap = "2.24"
mdbook = "0.2.1"
lazy_static = "1.1.0"
pulldown-cmark = "0.1.2"
pulldown-cmark-to-cmark = "1.1.0"
regex = "1"
serde_json = "1.0"
